### ISSUE TITLE
Improve Injector Doc

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#106]
Injector docs are improved and easier to maintained.

## Acceptance criteria
- [ ] Bernie's change are reviewed and are fit for purpose

## Pull request
- [ ] https://github.com/silverstripe/developer-docs/pull/105

**Comment by blueo** [comment]
@maxime-rainville anything else I need to do here to get this through?

**Comment by michalkleiner** [comment]
I went over it again and added a few small suggestions along the way. It even helped me refresh the stuff around DI in the CMS, so I think it's a good addition/improvement to the docs.

**Comment by blueo** [comment]
thanks again for the review @michalkleiner :) I've added those changes

**Comment by emteknetnz** [comment]
Linked PR has been merged
