### ISSUE TITLE
Maybe split the CMS 5 changelog

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#151]
The CMS5 change log is kind of massive. Let's have a chat with a bunch of dev to see if there's a more suitable way to split it for readability.

**Comment by GuySartorelli** [comment]
Seems to be fine, and this was buried in the backlog - unlikely to be actioned.

**Comment by michalkleiner** [comment]
When I was reading it the last time I was actually thinking whether we can hide some of the longer parts (e.g. the changed methods etc) in an accordion/show-hide section. The page is really long.

**Comment by GuySartorelli** [comment]
Good idea! We discussed that briefly this morning and Max will add it as a note to https://github.com/silverstripe/developer-docs/issues/194
