### ISSUE TITLE
Note down newly deprecated API in 4.13 changelog

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#172]
We updated a whole bunch of deprecation noticed for CMS 4.13 which included _adding_ deprecation notices that weren't there before (because we deleted the API in CMS 5).

We need to note this in the changelog, so people know what is _newly_ deprecated.
Probably we can re-purpose the tool @emteknetnz created to generate the changelog for CMS 5 API changes.

## PRs
- https://github.com/silverstripe/developer-docs/pull/180

**Comment by emteknetnz** [comment]
This tool https://github.com/emteknetnz/silverstripe-deprecator/blob/main/src/DeprecationDiffTask.php
