### ISSUE TITLE
SS5 beta changelog is missing removal of the MySQLPDODatabase class

### ISSUE THREAD

**Issue by Zazama** [silverstripe/developer-docs#185]
In https://github.com/silverstripe/silverstripe-framework/commit/03b929dd331f87b3a36f3c021c813a24529e29cc, the MySQLPDODatabase class has been removed from the _config/database.yml file of silverstripe/framework. This means that existing SS4 projects using

`SS_DATABASE_CLASS="MySQLPDODatabase"`

in their .env file have to change it to e.g. "MySQLDatabase".

The beta changelog has no mention of the removed class (only the commit message, which does not help with the error message).
I think the change should be mentioned under `Environment variable changes` to help with the error on upgrading.

PS: Thank you all for the work on SS5 :)

## Acceptance criteria
- [ ] CMS5 changelogs calls out that PDO is no longer supported in CMS5

**Comment by GuySartorelli** [comment]
Being done as a part of https://github.com/silverstripe/developer-docs/pull/186
