### ISSUE TITLE
Final review for CMS5 changelog

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#194]
## Acceptance criteria
- Consider if the changelog should be split in smaller chunks.
- Feedback from community and bespoke team is sought.
- Key area of improvements are outlined.
- Changelog is reviewed one final time and key improvement are applied.

## Note
- Maxime expect a thorough review of the changelog. This should take more than a day.
- Consider adding an "accordion" option to the full list of changelog (the same as the "Included module versions" list has)
- Refer to https://github.com/silverstripe/developer-docs/issues/253 for potential last-minute changes we might wanna do

## Pull request
- https://github.com/silverstripe/developer-docs/pull/255

**Comment by GuySartorelli** [comment]
PR merged.
