### ISSUE TITLE
CMS 5 upgrade pain: Changelog doesn't mention recommended replacements for removed API

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#203]
For API removed in CMS 5, the changelog says what was removed but is missing the "use x instead" or "removed without replacement" messages that the deprecation notices have.

For example, for `ViewableData::ThemeDir()` it says "Removed deprecated method SilverStripe\View\ViewableData::ThemeDir()" but it does not say what to use instead. You have to go look at the source code to see what the recommended replacement is.

We made a point of using the wording "clear upgrade path" when discussing CMS 5 upgrades, so it feels like this was an oversight. The replacement _is_ mentioned in deprecation notices in logs for actual projects, but this isn't so useful if you're just using the changelog to try produce an estimate for upgrades, for example.

I recommend we update [the doc writer Steve wrote](https://github.com/emteknetnz/silverstripe-deprecator) to pull in the "use x instead" part of deprecation messages, and run it again.

## Acceptance criteria
- Steve's magical tool is updated to take into consideration the actual depreciation message
- The magical tool is run one last time to update the changelog
- Any manual change that have already been made are retained

## PRs
- https://github.com/silverstripe/developer-docs/pull/252

**Comment by sabina-talipova** [comment]
@GuySartorelli, how I can check that ACs were completed?

**Comment by GuySartorelli** [comment]
> Steve's magical tool is updated to take into consideration the actual depreciation message

I pointed to my fork where the changes are - you can see that it's different from the original and that it looks for and uses the deprecation message.

> The magical tool is run one last time to update the changelog

You can see in the PR that the deprecation messages are there now - they're there because the tool was run.

> Any manual change that have already been made are retained

Look at the diff in the PR.

**Comment by sabina-talipova** [comment]
Changelog was updated correctly. Closed.
