### ISSUE TITLE
CMS 5 Doc Review - Extending Silverstripe CMS

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#217]
Review the [Extending Silverstripe CMS section](https://docs.silverstripe.org/en/5/developer_guides/extending/)

## Acceptance criteria
- All CMS 3 and CMS 4 examples are removed/updated for CMS 5 doc
- CMS 5 doc is reviewed with a focus on area with substantial change
  - including validate javascript examples still work

## Parent EPIC
https://github.com/silverstripe/developer-docs/issues/212

## PRs
- https://github.com/silverstripe/developer-docs/pull/273

**Comment by GuySartorelli** [comment]
I've done all "How_Tos/".
Also done _most_ of `00_Modules.md` - but still have to do the "Module Standard" part.
Haven't started on 01_ onwards.
