### ISSUE TITLE
Update changelog API changes to include fully qualified name of the classes

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/developer-docs#253]
## Description
Update changelog API changes to include fully qualified name of the classes which replaced deprecated functionality.
I believe that we should specify the fully qualified class name so that it does not raise questions about which particular class we mean, especially if they are in another module or just has another namespace.
### Related issue
- https://github.com/silverstripe/developer-docs/issues/203
#### Example
- https://github.com/silverstripe/developer-docs/blob/91551914320c698e8028d1257ef08bbae3f7f329/en/04_Changelogs/5.0.0.md?plain=1#L950

#### Note
See comments for:
- https://github.com/silverstripe/developer-docs/pull/252
- Having FQNS is a plus, but it's not the end of the world. Timebox this to 2 hours. Don't be too picky in peer review.

## Acceptance criteria
- Do a quick review to spot and update class references to use FQNS.

## PR
- https://github.com/silverstripe/developer-docs/pull/256

**Comment by GuySartorelli** [comment]
PR merged
