### ISSUE TITLE
Remove wrong links on api.silverstripe.org

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/developer-docs#259]
## Description
Remove link from the following list:
- [x] SilverStripe\FullTextSearch\Solr\Stores\SolrConfigStore_Post
- [x] SilverStripe\Admin\LeftAndMain.help_links
- [x] SilverStripe\BehatExtension\Context\BasicContext::iAttachTheFileToTheField()
- [x] SilverStripe\Comments\Admin\CommentsGridFieldApproveAction
- [x] SilverStripe\Comments\Admin\CommentsGridFieldSpamAction
- [x] SilverStripe\Comments\Admin\CommentsGridFieldBulkAction\SpamHandler
- [x] SilverStripe\Comments\Admin\CommentsGridFieldBulkAction\ApproveHandler instead
- [x] SilverStripe\Comments\Model\Comment::Parent()
- [x] SilverStripe\VendorPlugin
- [x] SilverStripe\SecurityExtensions
- [x] SilverStripe\Dev\Deprecation.currentlyEnabled
- [x] SilverStripe\Assets\Flysystem\FlysystemAssetStore::applyToFileIDOnFilesystem()
- [x] SilverStripe\CronTask\Controllers\CronTaskController.verbosity
- [x] SilverStripe\Core\CustomMethods::findMethodsFrom()
- [x] SilverStripe\Security\Member.title_format
- [x] SilverStripe\Control\Middleware\HTTPCacheControlMiddleware.defaultState
- [x] SilverStripe\Control\Middleware\HTTPCacheControlMiddleware.defaultForcingLevel
- [x] SilverStripe\Core\Manifest\ModuleManifest.module_priority
- [x] SilverStripe\Security\BasicAuthMiddleware.URLPatterns
- [x] SilverStripe\Dev\Deprecation.currentlyEnabled
- [x] SilverStripe\FullTextSearch

#### Update

- [x] SilverStripe\Subsites\State\SubsiteState\SubsiteState (UPDATE)
- [x] SilverStripe\View\Embed\EmbedResource (doesn't exist / deprecated since 4.13)
- [x] SilverStripe\Dev\DebugView::renderTrace() (doesn't work)
- [x] SilverStripe\Dev\DebugView::renderVariable() (doesn't work)
- [x] SilverStripe\Security\DefaultAdminService::getDefaultAdminUsername() (doesn't work)
- [x] SilverStripe\Control\Middleware\HTTPCacheControlMiddleware::setMaxAge() (doesn't work)

## PRs
- https://github.com/silverstripe/developer-docs/pull/261
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1354

**Comment by GuySartorelli** [comment]
PRs merged
