### ISSUE TITLE
V5 Preview MetaTag Code Example

### ISSUE THREAD

**Issue by Oliver996** [silverstripe/developer-docs#276]
The example for the MetaTags function in https://docs.silverstripe.org/en/5/developer_guides/customising_the_admin_interface/preview/#the-page-implementation is using the HTML4Value class that does not exist anymore in V5. I did change it to HTMLValue and that works for me. Is that the correct new class to use? Can you change the example?

### PRs
- https://github.com/silverstripe/developer-docs/pull/279

**Comment by emteknetnz** [comment]
Thanks for letting us know, I've created a pull-request to update this https://github.com/silverstripe/developer-docs/pull/279

**Comment by GuySartorelli** [comment]
PR merged
