### ISSUE TITLE
Move CMS 4 supported module list to developer doc to align with CMS 5

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#278]
We still have a list of supported module for CMS 4 here: https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/

## Acceptance criteria
- An equivalent page is created in the CMS 4 doc.
- The current DotORG page redirects to the doc (don't include a version number in the redirection link - that will ensure it directs to the most recent version).
- The CMS 4 and CMS 5 supported modules doc pages link to each other and make explicit that module support will vary from version to version.

## PRs
- https://github.com/silverstripe/developer-docs/pull/296
- https://github.com/silverstripe/developer-docs/pull/297

**Comment by GuySartorelli** [comment]
Doc merged, no remaining ACs

**Comment by GuySartorelli** [comment]
Oops, there is a remaining AC. Reassigning to @emteknetnz to change page on .org to redirect to docs

**Comment by emteknetnz** [comment]
Have changed https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list to a redirector page

**Comment by GuySartorelli** [comment]
Perfect. _now_ all ACs are done. Closing.
