### ISSUE TITLE
Example Enum throws errors when used

### ISSUE THREAD

**Issue by b-rhodes** [silverstripe/developer-docs#288]
One of the examples (shown below) on the [Data Types page](https://docs.silverstripe.org/en/5/developer_guides/model/data_types_and_casting/#default-values) has an error with the enum used in the `$db` array.
If you try to actually use this it throws an error.
To get it to actually work I had to do this: `'Enum("New,Fair,Junk", "Fair")'`.

```php
use SilverStripe\ORM\DataObject;

class Car extends DataObject 
{   
    private static $db = [
        'Wheels' => 'Int(4)',
        'Condition' => 'Enum(["New","Fair","Junk"], "Fair")',
        'Make' => 'Varchar(["default" => "Honda"])',
    ];
}
```

## Pull request
- #290

**Comment by GuySartorelli** [comment]
PR merged
