### ISSUE TITLE
Review best practice for drafting documentation in the developer docs

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#302]
We expect to be doing a fair bit of documentation over the next couple months. It would be helpful to agree on some common best practices when drafting doc.

## Acceptance criteria
- ~Liaise with the Silverstripe Content Writer upfront to make sure the guide lines line ups with Silverstirpe other style guide.~
- Existing documentation best practices are reviewed.
- New best practices are agreed upon.
- Validate if the generic style guide should apply to the doc and make sure relevant rules are available to the public.

## Notes
- This should not encompass docblock in our PHP code. We will spin up a separate card for it.

## Related
- https://github.com/silverstripe/developer-docs/issues/473

## PRs
- https://github.com/silverstripe/developer-docs/pull/494
- https://github.com/silverstripe/developer-docs/pull/512

**Comment by GuySartorelli** [comment]
PR merged.
