### ISSUE TITLE
Some recently merged things should have had documentation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#318]
The following were merged and closed recently but should have had additional documentation:

- https://github.com/silverstripe/silverstripe-admin/issues/1539
    Need to document that it's available in CMS 4 docs
    Need to call it out in CMS 5.1 changelog
- https://github.com/silverstripe/silverstripe-framework/issues/10761
    Need to call it out in CMS 5.1 changelog
    
## PRs
- https://github.com/silverstripe/developer-docs/pull/319 (cms 4)
- https://github.com/silverstripe/developer-docs/pull/320 (cms 5)

**Comment by emteknetnz** [comment]
Linked PRs have been merged
