### ISSUE TITLE
Call out IP anonimisation in session manager

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#321]
@lekoala just did an [awesome PR to anonymise IP](https://github.com/silverstripe/silverstripe-session-manager/pull/161) in session manager and facilitate GDPR compliance.

This should be called out in the 5.1 changelog.

## Acceptance criteria
- The 5.1 changelog highlights the new IP anonymising capability and how to use it.

## PRs
- https://github.com/silverstripe/developer-docs/pull/326

**Comment by GuySartorelli** [comment]
PR merged
