### ISSUE TITLE
Migrate sesion manager doc to main doc

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#322]
Session manager is a core module that gets installed by default. Seems sensible to manage its docs along with the main doc

## Acceptance criteria
- All the session manager doc currently stored on the repo is migrated to an appropriate section of the developer docs.
- Only the CMS 5 doc is migrated.
- Documentation is removed from the session manager repo and links to our regular docs instead.

## PRs
- https://github.com/silverstripe/developer-docs/pull/327
- https://github.com/silverstripe/silverstripe-session-manager/pull/164

**Comment by GuySartorelli** [comment]
@emteknetnz Please migrate the docs from the readme as well.

**Comment by emteknetnz** [comment]
@GuySartorelli done

**Comment by GuySartorelli** [comment]
PRs merged.
