### ISSUE TITLE
Sub topic arrangement

### ISSUE THREAD

**Issue by izzudin96** [silverstripe/developer-docs#334]
Hi,

Wondering the reason behind the subtopic is arrange differently.

Example:

![image](https://github.com/silverstripe/developer-docs/assets/34004451/38a06074-75fd-462c-9116-62da1b55b12c)

We can see `Adding DataObjects to the schema` is the first item.

But in the subtopic page, it is arrange second

![image](https://github.com/silverstripe/developer-docs/assets/34004451/d9ef22eb-9d61-430d-a742-566785c1229d)

Is there particular way of reading the sub topics?

**Comment by GuySartorelli** [comment]
There have been a bunch of different people in charge of creating documentation over the years and there's no specific guidelines for how to arrange them (or if there are, they haven't been consistently followed).

Improving the IA of the docs is a very large task that is in our backlog but we don't have any specific timeline for doing.
