### ISSUE TITLE
Add silverstripe/dynamodb as a supported module for CMS 5

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#338]
[silverstripe/dynamodb](https://github.com/silverstripe/silverstripe-dynamodb/) is required for at least one of silverstripe cloud and silverstripe cloud public sector.
It should be commercially supported - and it's already in kitchen sink.

## Acceptance criteria
- silverstripe/dynamodb is listed as commercially supported in the docs for cms 5
- silverstripe/dynamodb is added to the supported-modules repo if it's not there already
- Validate that silverstripe/dynamodb is in the sink and gets picked up when we tag releases.
 
## PRs
- https://github.com/silverstripe/supported-modules/pull/25
- https://github.com/silverstripe/supported-modules/pull/26
- https://github.com/silverstripe/developer-docs/pull/342
- https://github.com/silverstripe/developer-docs/pull/343

**Comment by emteknetnz** [comment]
Have confirmed that dynamodb will show up in a new cow plan

![image](https://github.com/silverstripe/developer-docs/assets/4809037/25d3855e-83d0-489f-982e-50acebd0340d)

**Comment by GuySartorelli** [comment]
PRs merged
