### ISSUE TITLE
Encourage use of `shuffle()` instead of `orderBy()`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#354]
We shouldn't encourage using `orderBy()` for random sorting - that's what the `shuffle()` abstraction is for.
Instead, don't mention `orderBy()` at all until the dedicated raw SQL section.

## PRs
- https://github.com/silverstripe/developer-docs/pull/353

**Comment by sabina-talipova** [comment]
PR merged.
