### ISSUE TITLE
Review our OSS contribution doc

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#360]
This issue used to be https://github.com/silverstripeltd/product-issues/issues/783 but there was no need for it to be private.

At Stripecon 2023 we're giving a talk that aims to promote contributions to Silverstripe CMS open source. We should make sure our documentation is up to date so that people can contribute confidently and effectively.

## Acceptance criteria
- Review and streamline our [contribution doc](https://docs.silverstripe.org/en/contributing/)
- Validate the doc and the doc update with our bespoke teams

## Notes
- Symfony has some great examples on this front:
  -  https://symfonycasts.com/screencast/contributing
  -  https://symfony.com/doc/current/contributing/index.html
- Ignore the release process doc which will be handled in https://github.com/silverstripeltd/product-issues/issues/815
- Ignore the coding conventions doc which will be handled in https://github.com/silverstripe/developer-docs/issues/323
  
## PRs
**IMPORTANT** These are likely to have significant merge conflicts with CMS 5 docs. When you have merged all the PRs, reassign to Guy so they can merge up and resolve the conflicts.
### Just content changes
Just updating content - not moving anything, ideally
- https://github.com/silverstripe/developer-docs/pull/357
- https://github.com/silverstripe/developer-docs/pull/358
- https://github.com/silverstripe/developer-docs/pull/359
- https://github.com/silverstripe/developer-docs/pull/361
- https://github.com/silverstripe/developer-docs/pull/362
- https://github.com/silverstripe/developer-docs/pull/367
- https://github.com/silverstripe/developer-docs/pull/368
- https://github.com/silverstripe/developer-docs/pull/369
- https://github.com/silverstripe/developer-docs/pull/370
- https://github.com/silverstripe/developer-docs/pull/371
- https://github.com/silverstripe/developer-docs/pull/372

### Content and some structural changes
Updates to content, and moving content around between pages
- https://github.com/silverstripe/developer-docs/pull/378
- https://github.com/silverstripe/developer-docs/pull/379
- https://github.com/silverstripe/developer-docs/pull/380
- https://github.com/silverstripe/developer-docs/pull/381
- https://github.com/silverstripe/developer-docs/pull/382
- https://github.com/silverstripe/developer-docs/pull/383
- https://github.com/silverstripe/developer-docs/pull/384

### Pure structural changes
Reordering pages altogether
- https://github.com/silverstripe/developer-docs/pull/385

**Comment by GuySartorelli** [comment]
@emteknetnz Looks like you've approved a lot of PRs but not merged anything?

**Comment by emteknetnz** [comment]
Assigned back to @GuySartorelli for `Steps required after merging the below PRs`

**Comment by GuySartorelli** [comment]
Reopening for the remaining todo stuff

**Comment by emteknetnz** [comment]
@GuySartorelli have merged the new PR - is there anything left? You can probably re-close?

**Comment by GuySartorelli** [comment]
That's all this time
