### ISSUE TITLE
Document nested request handlers

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#401]
Following some [internal discussion](https://github.com/silverstripe/silverstripe-admin/issues/1589), we've concluded that we haven't properly documented and explained our approach no nested controllers, especially in the context of creating AJAX request endpoints.

## Acceptance criteria
- A new article is added to the developer docs explaining how nested request handlers work
- A CMS developer should be able to create nested request in the CMS after reading that article
- The article is drafted with the expectation that it will be complemented with other approaches for non-nested request handlers.
- The arcticle is linked to from the routing docs

## Related
- There's a bit of PHP doc comment that provides good context on this in the Request Handler class.

## PRs
- https://github.com/silverstripe/developer-docs/pull/415

**Comment by GuySartorelli** [comment]
PR merged
