### ISSUE TITLE
Document current approach to creating API endpoints in the CMS

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#422]
## Acceptance criteria
- Common approach to creating CMS endpoints in the CMS are identified and documented.
- Common pitfall (e.g. permissions check, error handling) are called out.
 
## Related
- https://github.com/silverstripe/silverstripe-admin/issues/1589

## Follow up card
- Document explains how to create Form Schema (Maybe spin up as a separate card and go into the JS part as well.)

## Notes
- `private static string $required_permission_codes = 'CMS_ACCESS_CMSMain';` is required on LinkFieldController so that non-admins can access endpoints, so possibly this is general a requirement for all controllers that extend LeftAndMain

## PRs
- https://github.com/silverstripe/developer-docs/pull/445
- https://github.com/silverstripe/silverstripe-admin/pull/1658
- https://github.com/silverstripe/silverstripe-linkfield/pull/184

**Comment by GuySartorelli** [comment]
Assigning back to Steve to do whatever needs done with the linkfield PR (haven't looked at it yet)

**Comment by GuySartorelli** [comment]
PRs merged
