### ISSUE TITLE
Add docs for generic lazy loading feature

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#426]
The GridField lazyloading functionality was made generic in [1.12.0](https://github.com/silverstripe/silverstripe-admin/releases/tag/1.12.0)

Context:
-  https://github.com/silverstripe/silverstripe-admin/issues/1308

## PRs
- https://github.com/silverstripe/developer-docs/pull/427

**Comment by sabina-talipova** [comment]
PR is merged.
