### ISSUE TITLE
Review 5.2 changelog

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#472]
As a developer contemplating a 5.2 upgrade, I want clear and concise information about what has changed so I can plan my upgrade with ease.

## Acceptance criteria

1. [x] List of commits is reviewed to identify noteworthy changes not currently appearing in the main body of changelog.
2. [x] Full changelog is reviewed for readability and to make sure no key details are missing.
3. [x] Changelog follows our [Web Writing Style Guide](https://silverstripe.atlassian.net/wiki/spaces/MAR/pages/506364107/Silverstripe+Writing+Style+Guide) (only available to Silverstripe staff).
4. [x] Since the linkfield migrations didn't make it, changelog gives some indication about what to do if updating from an old version of linkfield.

## Exclude
- Warning about the change of support level for 4.

## PRs
- https://github.com/silverstripe/developer-docs/pull/482

**Comment by sabina-talipova** [comment]
PR has been merged. Task is completed.
