### ISSUE TITLE
Writing style guide doesn't match company writing style guide

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#473]
The [writing style guide](https://docs.silverstripe.org/en/5/contributing/documentation/#writing-style) for Silverstripe CMS docs doesn't include everything from the company style guide in confluence.
There is a chance there are conflicts between the two, as well.

## To decide
- To what extent do the docs need to follow the company style guide?
    - Take into account that the company style guide has changed and may change again outside of our control
        - keeping the docs up to date with those changes may be difficult
        - We ideally don't want to update the style guide for new docs, which then end up reading completely different from existing docs.

**Comment by michalkleiner** [comment]
As much as everyone appreciates the company's contribution to the project I think certain things could/should be independent and it should be the OS CMS hat to wear first ;-)

**Comment by GuySartorelli** [comment]
I 10000% agree. This card came about because of https://github.com/silverstripe/developer-docs/issues/472 which says to use the company style guide.

**Comment by GuySartorelli** [comment]
https://github.com/silverstripe/developer-docs/issues/302 is bringing *some* parity between the two - I think we can all agree to put this to rest once that's finished and merged, and just use the publicly documented style guide henceforth.
