### ISSUE TITLE
Update PHP coding standards to avoid using `self`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#486]
We had a bug which it turned out was caused by an unexpected interaction between `self` and late static binding (see [this PR](https://github.com/silverstripe/silverstripe-linkfield/pull/262)).
This was [raised in php-src](https://github.com/php/doc-en/issues/3293) where the response was that it was working as intended.

Going forward we should avoid calling static methods from `self` to avoid this class of bug.

## Notes
- In refinement we decided it's easiest to just avoid using `self` altogether, rather than only avoiding it for calling methods

## Acceptance Criteria
- [x] The [PHP coding standards](https://docs.silverstripe.org/en/5/contributing/coding_conventions/php_coding_conventions/) are updated to explicitly disallow using `self` (e.g. `self::get()`)
- [x] The docs mention the rationale, i.e. we're avoiding a specific class of bug that is introduced when using late static binding downstream from `self`
- [x] `static` is fine, because it explicitly uses late static binding anyway
- [x] References to `self` in our codebase are updated to use the actual class that is intended to received the call.
- [x] Update code-writing script and re-run to use `self::class::myMethod()` in traits

## Code writing script
- https://github.com/emteknetnz/self-remover

## Kitchen sink CI
- https://github.com/emteknetnz/recipe-kitchen-sink/actions/runs/9514611296

## PRs
- https://github.com/silverstripe/developer-docs/pull/528
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/90
- https://github.com/silverstripe/cwp-agencyextensions/pull/123
- https://github.com/silverstripe/cwp/pull/337
- https://github.com/silverstripe/cwp-core/pull/131
- https://github.com/silverstripe/silverstripe-elemental/pull/1201
- https://github.com/silverstripe/silverstripe-admin/pull/1773
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1467
- https://github.com/silverstripe/silverstripe-assets/pull/614
- https://github.com/silverstripe/silverstripe-behat-extension/pull/274
- https://github.com/silverstripe/silverstripe-blog/pull/761
- https://github.com/silverstripe/silverstripe-cms/pull/2955
- https://github.com/silverstripe/silverstripe-config/pull/115
- https://github.com/silverstripe/silverstripe-contentreview/pull/237
- https://github.com/silverstripe/silverstripe-crontask/pull/89
- https://github.com/silverstripe/silverstripe-documentconverter/pull/83
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/104
- https://github.com/silverstripe/silverstripe-errorpage/pull/110
- https://github.com/silverstripe/silverstripe-event-dispatcher/pull/25
- https://github.com/silverstripe/silverstripe-externallinks/pull/129
- https://github.com/silverstripe/silverstripe-framework/pull/11270
- https://github.com/silverstripe/silverstripe-frameworktest/pull/183
- https://github.com/silverstripe/silverstripe-graphql/pull/590
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/106
- https://github.com/silverstripe/silverstripe-ldap/pull/80
- https://github.com/silverstripe/silverstripe-linkfield/pull/295
- https://github.com/silverstripe/silverstripe-login-forms/pull/181
- https://github.com/silverstripe/silverstripe-lumberjack/pull/152
- https://github.com/silverstripe/markdown-php-codesniffer/pull/10
- https://github.com/silverstripe/silverstripe-mfa/pull/545
- https://github.com/silverstripe/MinkFacebookWebDriver/pull/27
- https://github.com/silverstripe/silverstripe-realme/pull/144
- https://github.com/silverstripe/recipe-plugin/pull/43
- https://github.com/silverstripe/silverstripe-reports/pull/184
- https://github.com/silverstripe/silverstripe-restfulserver/pull/127
- https://github.com/silverstripe/silverstripe-securityreport/pull/81
- https://github.com/silverstripe/silverstripe-session-manager/pull/198
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/238
- https://github.com/silverstripe/silverstripe-siteconfig/pull/164
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/92
- https://github.com/silverstripe/silverstripe-spamprotection/pull/118
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/192
- https://github.com/silverstripe/silverstripe-subsites/pull/575
- https://github.com/silverstripe/silverstripe-tagfield/pull/291
- https://github.com/silverstripe/silverstripe-testsession/pull/90
- https://github.com/silverstripe/silverstripe-textextraction/pull/95
- https://github.com/silverstripe/silverstripe-userforms/pull/1299
- https://github.com/silverstripe/vendor-plugin/pull/78
- https://github.com/silverstripe/silverstripe-versioned/pull/449
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/344
- https://github.com/silverstripe/silverstripe-versionfeed/pull/111
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/183
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/537
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/402
- https://github.com/symbiote/silverstripe-queuedjobs/pull/432
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/859
- https://github.com/silverstripe/silverstripe-graphql/pull/592

**Comment by maxime-rainville** [comment]
Is there an actual issue that got cause by this? e.g. Did we have a scenario where we called `self::get()` in `Link` wanting to query all Links and ended up querying only `FileLink`.

**Comment by GuySartorelli** [comment]
> Is there an actual issue that got cause by this?

Yes. I'll link you the slack thread.

**Comment by GuySartorelli** [comment]
PRs merged.
I've raised https://github.com/silverstripe/silverstripe-standards/issues/8 to add a rule in CI to catch this happening in the future.
