### ISSUE TITLE
Update optional docs

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/developer-docs#492]
- Change "Silverstripe elemental" top level title to "Elemental"
- Screenshots on https://docs.silverstripe.org/en/5/optional_features/elemental/basic_setup/ doesn't show
- userforms showing some readme level stuff code-of-conduct, contribution etc - https://docs.silverstripe.org/en/5/optional_features/userforms/

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1165
- https://github.com/silverstripe/doc.silverstripe.org/pull/296

**Comment by GuySartorelli** [comment]
PRs merged and look good on the site
