### ISSUE TITLE
Hint not rendering

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/developer-docs#503]
https://docs.silverstripe.org/en/5/developer_guides/forms/validation/

![image](https://github.com/silverstripe/developer-docs/assets/4809037/d9655d75-3d32-4418-ba02-b29058da65a5)

## PR
- https://github.com/silverstripe/developer-docs/pull/504

**Comment by GuySartorelli** [comment]
Should be `TIP` not `HINT`

**Comment by GuySartorelli** [comment]
PR merged and hint now rendering correctly.
