### ISSUE TITLE
Display CMS 6 docs on docs.silverstripe.org and api.silverstripe.org

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/developer-docs#573]
## Acceptance criteria
- [x] A CMS 6 version on https://docs.silverstripe.org/ is created
- [x] CMS 5 docs remain the default
- [x] CMS 6 docs get a banner showing that it's in pre-release
- [ ] api.silverstripe.org also has a CMS 6 version

## PRs
- https://github.com/silverstripe/supported-modules/pull/41
- https://github.com/silverstripe/doc.silverstripe.org/pull/308
- https://github.com/silverstripe/api.silverstripe.org/pull/121

**Comment by GuySartorelli** [comment]
PRs merged.
Api docs failed deployment, but we want to [move those to GitHub Pages](https://github.com/silverstripe/api.silverstripe.org/issues/122) anyway.

Just waiting for the docs sites to deploy.

**Comment by GuySartorelli** [comment]
Docs sites deployed and look good
