### ISSUE TITLE
Missing Quote on Route example

### ISSUE THREAD

**Issue by catharsisjelly** [silverstripe/developer-docs#611]
### Pages affected

- [Routing](https://docs.silverstripe.org/en/5/developer_guides/controllers/routing/)

### Description

There is a `'` missing in the example for creating an admin route

### Validations

- [X] Check that there isn't already an issue that reports the same problem

## PRs
- https://github.com/silverstripe/developer-docs/pull/617

**Comment by GuySartorelli** [comment]
PR merged
