### ISSUE TITLE
URL for React Dev tools not working

### ISSUE THREAD

**Issue by catharsisjelly** [silverstripe/developer-docs#618]
### Pages affected

- [React, Redux, and GraphQL](https://docs.silverstripe.org/en/5/developer_guides/customising_the_admin_interface/reactjs_redux_and_graphql/)

### Description

The URL for the plugin has a bad URL. I'm also going to suggest we move the link to be on the relevant browser e.g [Chrome](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) and then link in the one for Firefox too.

### Validations

- [X] Check that there isn't already an issue that reports the same problem

## PRs
- https://github.com/silverstripe/developer-docs/pull/619

**Comment by GuySartorelli** [comment]
PR merged
