### ISSUE TITLE
Migrate update content to changelogs for CMS 5

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#74]
I started out listing breaking changes in the update docs (with the intention that it would be used to create a more how-to style document later on), and then ended up putting a more how-to write up in the changelogs because that's the kind of content we normally add there - because we normally aren't doing major releases.

I think we should be listing the explicit breaking changes (removed x, use y instead) in the changelog, and then anything that requires further explanation should be in the upgrade docs.

This issue exists both to facilitate discussion about that in case anyone disagrees, and then to actually set up the docs in whichever manner is agreed upon.

## Acceptance criteria
- [x] It is clear for CMS 5 which content goes into the update docs and what content goes into the changelog
- [x] CMS5 upgrade guide should be folded back into changelog
- [x] Update existing PR that adds entry to the upgrade guide to target the changelog instead (BLOCKED pending the attached PR being merged)

## PRs
- https://github.com/silverstripe/developer-docs/pull/84

**Comment by maxime-rainville** [comment]
We've decided to put everything in the CMS 5 changelog initially. As we got closer to CMS 5 Beta 1, we will re-evaluate the need for a dedicated upgrade guide.

**Comment by GuySartorelli** [comment]
Note that I can't update the existing PRs until the attached PR is merged.

**Comment by GuySartorelli** [comment]
Done
