### ISSUE TITLE
Docs aren't updated when PRs are merged into 5 branch

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/developer-docs#77]
Currently when the 5 branch gets new content merged in, we have to manually deploy the changes.
The workflow should be updated to deploy when the 5 branch gets pushes.

## Acceptance criteria
- [ ] When new content is pushed to the `5` branch, the site is deployed
- [ ] The site can be deployed by running the workflow manually

## PRs
- https://github.com/silverstripe/developer-docs/pull/76

**Comment by maxime-rainville** [comment]
When I try to manually trigger the workflow on the 5 branch I get this error.

![image](https://user-images.githubusercontent.com/1168676/193547521-c1eb82bb-9875-4ce9-bfd3-6eaedeecf96e.png)

**Comment by GuySartorelli** [comment]
It just needs to be merged up - but also the manual dispatch doesn't need a specific branch, it rebuilds the whole site any time it's run anyway.

**Comment by GuySartorelli** [comment]
Merged up to 5 and the action ran:
https://github.com/silverstripe/developer-docs/actions/runs/3185954192
