### ISSUE TITLE
Document how deprecation works

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#82]
We don't have clear guidance on how and when to deprecate method and classes.

## Acceptance criteria
- [x] Developers have clear guidance on how to activate/deactivate deprecation warnings and how to configure them.
  - [x] That guidance can be applied to unit test and to browser based execution as well.
- [x] Developers planning a CMS5 upgrade are encouraged to turn on deprecation warnings on their CMS4 project as way to facilitate their upgrade.
- [x] The doc explicitly tells developers working on the core product 
  - [x] how and when to use `@deprecated` phpdoc annotation
  - [x] how and when to use `Deprecation::notice()`
  - [x] how to retain test for deprecated code
  - [x] how to validate that that deprecated code is no longer in use by the non-deprecated code base.
- [x] Review any previous docs about deprecation and make sure it's inline with the new doc or remove it altogether.

## Note 
- Once upon a time, some folks wanted to have a PSR standard that would require people to write their deprecation annotations like `@deprecated 4.1.0:5.0.0 Some description`. In this scenario, 4.1.0 would be the version where the method got deprecated and 5.0.0 would be the version where the method is expected to be remove. The [second version parameter got dropped](https://github.com/php-fig/fig-standards/pull/1117). But we still use that syntax in a few places.
- [Draft PSR19 standard proposal for `@deprecated`](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#54-deprecated)

## PRs
- https://github.com/silverstripe/developer-docs/pull/131

**Comment by GuySartorelli** [comment]
Why has this been created under userhelp? Content authors shouldn't be expected to know or care about this.

**Comment by maxime-rainville** [comment]
Because I'm a dummy.

**Comment by GuySartorelli** [comment]
PR merged
